# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ulyUPn-5FGL0Pd1hQOcii4H0G8_UvUv0
"""

import streamlit as st
import json
from chatbot_responses import predict_class, get_response
import nltk

nltk.data.path.append('/tmp')
nltk.download('punkt', download_dir='/tmp')
nltk.download('wordnet', download_dir='/tmp')
nltk.download('omw-1.4', download_dir='/tmp')

st.set_page_config(page_title="Student FAQ Chatbot", layout="centered")
st.title("🎓 Student FAQ Chatbot")
st.markdown("Ask me anything about college admissions, campus life, or more!")

user_input = st.text_input("You:")

if user_input:
    ints = predict_class(user_input)
    res = get_response(ints, json.loads(open("intents.json").read()))
    st.text_area("Chatbot:", value=res, height=100, max_chars=None)
